spring:
  application:
    name: live-stream-recorder
  profiles:
    group:
      dev:
        - dev
      prod:
        - prod
    active: dev

youtube:
  google-api:
    key: ${youtube-google-api-key}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
