spring:
  datasource:
    url: jdbc:postgresql://${database.url}/${database.name}
    username: ${database.username}
    password: ${database.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false

logging:
  config: classpath:logback/logback-prod.xml